CREATE TABLE IF NOT EXISTS public.media (
	id BIGSERIAL PRIMARY KEY,
	nome CHARACTER VARYING(255) NOT NULL,
	descricao CHARACTER VARYING(255),
	content_type CHARACTER VARYING(255) NOT NULL,
	url CHARACTER VARYING(255),
	duracao BIGINT DEFAULT 0,
	data_upload DATE NOT NULL DEFAULT NOW(),	
	deletado BOOLEAN NOT NULL DEFAULT FALSE
);